# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 623)
        MainWindow.setStyleSheet("*{\n"
"     font-family: dengxian;\n"
"     font-size: 18px;\n"
"     color: #1d649c;\n"
"  }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_update = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update.sizePolicy().hasHeightForWidth())
        self.pushButton_update.setSizePolicy(sizePolicy)
        self.pushButton_update.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"    font-size: 18px;\n"
"}")
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_3.addWidget(self.pushButton_update)
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete.sizePolicy().hasHeightForWidth())
        self.pushButton_delete.setSizePolicy(sizePolicy)
        self.pushButton_delete.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"    font-size: 18px;\n"
"}")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_3.addWidget(self.pushButton_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setStyleSheet("")
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_2.addWidget(self.lineEdit_input)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setStyleSheet("QPushButton {\n"
"    color: green;\n"
"    font-size: 18px;\n"
"}")
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_2.addWidget(self.pushButton_search)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    font-size: 18px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.plainTextEdit_text1_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_text1_2.setStyleSheet("QPlainTextEdit{\n"
"    background.py-color: rgb(211, 193, 255)\n"
"}")
        self.plainTextEdit_text1_2.setObjectName("plainTextEdit_text1_2")
        self.verticalLayout_3.addWidget(self.plainTextEdit_text1_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setStyleSheet("QLabel {\n"
"    color: blue;\n"
"    font-size: 18px;\n"
"}")
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.plainTextEdit_text_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_text_1.setStyleSheet("QPlainTextEdit{\n"
"    background.py-color: rgb(170, 255, 255)\n"
"}")
        self.plainTextEdit_text_1.setObjectName("plainTextEdit_text_1")
        self.verticalLayout_2.addWidget(self.plainTextEdit_text_1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "测试窗口_1"))
        self.pushButton_update.setText(_translate("MainWindow", "更新"))
        self.pushButton_delete.setText(_translate("MainWindow", "清除"))
        self.lineEdit_input.setText(_translate("MainWindow", "请输入关键词"))
        self.pushButton_search.setText(_translate("MainWindow", "查找"))
        self.label_2.setText(_translate("MainWindow", "文本框"))
        self.label_1.setText(_translate("MainWindow", "文本框"))
